### ISSUE TITLE
Forge Server Crash on Startup

### ISSUE THREAD

**Issue by royboydotcom** [sunbatheproductions/guardribbits#1]
My dedicated Forge server crashes on startup when GuardRibbits is added. Log file is attached.
[latest.log](https://github.com/user-attachments/files/18138622/latest.log)

[14Dec2024 21:08:04.742] [main/ERROR] [net.minecraft.resources.RegistryDataLoader/]: Registry loading errors:
> Errors in registry minecraft:worldgen/template_pool:
>> Errors in element ribbits:ribbits:
java.lang.IllegalStateException: Failed to parse ribbits:worldgen/template_pool/ribbits.json from pack GuardRibbits-1.20.1-Forge-1.0.5.jar
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.resources.RegistryDataLoader.m_255048_(RegistryDataLoader.java:147)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.resources.RegistryDataLoader$RegistryData.m_254786_(RegistryDataLoader.java:161)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.resources.RegistryDataLoader.m_254785_(RegistryDataLoader.java:63)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.resources.RegistryDataLoader.m_247207_(RegistryDataLoader.java:62)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.WorldLoader.m_246152_(WorldLoader.java:54)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.WorldLoader.m_245736_(WorldLoader.java:58)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.WorldLoader.m_214362_(WorldLoader.java:31)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Main.lambda$main$2(Main.java:167)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.Util.m_214652_(Util.java:777)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.Util.m_214679_(Util.java:772)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Main.main(Main.java:166)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.0/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.lang.RuntimeException: No key fallback in MapLike[{"replace":false,"elements":[{"weight":1,"element":{"location":"ribbits:ribbits/guard_ribbit","processors":"ribbits:main","projection":"rigid","element_type":"yungsapi:yung_single_element"}}]}]
	at MC-BOOTSTRAP/datafixerupper@6.0.8/com.mojang.serialization.DataResult.lambda$getOrThrow$5(DataResult.java:101)
	at MC-BOOTSTRAP/datafixerupper@6.0.8/com.mojang.datafixers.util.Either$Right.map(Either.java:99)
	at MC-BOOTSTRAP/datafixerupper@6.0.8/com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.resources.RegistryDataLoader.m_255048_(RegistryDataLoader.java:143)
	... 26 more

**Comment by royboydotcom** [comment]
Issue is resolved with version 1.0.6. Everything works normally!
